#!/bin/bash

set -e
set -x

# should use inotifywait to see if files are put in directory.
#JOBDIR = /srv/batchd/jobs
#WORKDIR=/srv/batchd/work and then you cahn choose if that is tmpfs or whatever
JOBDIR=$(pwd)/jobs
OUTDIR=$(pwd)/output
basedir=$(pwd)

function exec_job {
	file=$1
	workdir=$(mktemp -d)
	echo Executing job $file in dir $workdir

	# Maybe keep the file on error, but somehow mark it as failed?
	mv $JOBDIR/$file $workdir
	cd $workdir

	# Make sure all files exist.
	touch STD{IN,OUT,ERR}

	# Go to end on error, continue on success.
	tar -xmf $file 2>STDERR && {
		echo Running job...
		./run <STDIN 1>STDOUT 2>STDERR || true
		newfiles=$(find . ! -name ".*" -cnewer STDOUT)
	} || {
		echo Unpack failed.
		newfiles="STDIN STDOUT STDERR"
	}

	echo $(echo $newfiles|wc -l) files created/changed.
	echo $newfiles

	# Use file suffix to choose compressor, or default to gzip
	tar -caf $OUTDIR/$file $newfiles

	cd $basedir
	rm -rf $workdir
}

file=$(basename $(ls -drc $JOBDIR/*|head -n 1))

exec_job $file

exit 0
